### ISSUE TITLE
Armored Mobs

### ISSUE THREAD

**Issue by DragonGodGrapha** [SgtPunishment/Soul-Shards-The-Old-Ways-1.7.10#25] opened 2015-02-08 05:17 UTC
I've been messing around in creative to see if it would be reasonable to farm the Thaumcraft Crimson mobs, but I found that they spawn without armor, even though they have a 100% chance to have this armor. A fix for the "100% chance of armor" case would be nice, but I'd understand why if it couldn't work out.

**Comment by CorvusUrro** [comment] 2015-02-08 08:04
What version are you using, Because I think we fixed this bug already

**Comment by DragonGodGrapha** [comment] 2015-02-08 18:51
I'm using rc7a. You can see all the unarmored ones which were spawned, and the spawn-egged ones, fully armored like the one I started the shard with.

![2015-02-08_12 46 04](https://cloud.githubusercontent.com/assets/9646692/6097834/08e7723a-af91-11e4-9aba-1237aa2327e9.png)

**Comment by SgtPunishment** [comment] 2015-03-06 21:37
Sorry for taking so long to respond, but I've gone over our previous issues, and Unstoppable said he fixed this issue before? Was it fixed then stopped working or did the fix not work at all?

**Comment by UnstoppableN** [comment] 2015-03-07 23:28
Could not reproduce this issue ![Could not reproduce](http://i.imgur.com/UJxGFic.png)
Make sure your shard is also created with the latest version of sstow (the armor is saved to the shard during the shard creation)

**Comment by DragonGodGrapha** [comment] 2015-03-07 23:40
Is it potentially an issue if using a blank tier 5 to make them? I figured it just acted as if it killed the specified mob enough times, but I'm not entirely sure.

**Comment by UnstoppableN** [comment] 2015-03-08 00:03
Thank you for this description. I always kill one entity and use the /sstow addkills [amount] command so I hadn't noticed this issue. The new code is sent to the sarge (project leader). This will probably be fixed in the next release.

**Comment by SgtPunishment** [comment] 2015-03-08 19:29
I can confirm that this has been fixed in the latest commit
https://github.com/SgtPunishment/Soul-Shards-The-Old-Ways-1.7.10/commit/29a7921c5140f787e7ef246b0f84ab4430794dae

**Closed by SgtPunishment** 2015-03-08 19:29 UTC
